import { createClient } from '@sanity/client'
import { createGroqBuilder, makeSafeQueryRunner } from 'groqd'

// Import Sanity types, generated by Sanity project.
import type * as SanityTypes from './sanity.types.ts'
import { buildSrc, ImageSrcInputs } from '@sanity-image/url-builder'

const [_, projectId, dataset, token] = import.meta.env.VITE_DATA_PROVIDER.split(
  ':'
)
const sanityConfig = {
  projectId,
  dataset,
  useCdn: true,
  apiVersion: '2026-04-07',
  token,
}

const sanityClient = createClient(sanityConfig)

export const runQuery = makeSafeQueryRunner((query) =>
  sanityClient.fetch(query)
)

type SchemaConfig = {
  schemaTypes: SanityTypes.AllSanitySchemaTypes
  referenceSymbol: typeof SanityTypes.internalGroqTypeReferenceTo
}
export const q = createGroqBuilder<SchemaConfig>({})

export const urlFor = (
  assetId: string | undefined | null,
  options: Omit<ImageSrcInputs, 'id' | 'baseUrl'>
) =>
  assetId
    ? buildSrc({
        id: assetId,
        baseUrl: `https://cdn.sanity.io/images/${sanityConfig.projectId}/${sanityConfig.dataset}/`,
        ...options,
      }).src
    : null
