/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type TournamentReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'tournament'
}

export type PlayerReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'player'
}

export type TournamentTeamReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'tournament-team'
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type TournamentPlayer = {
  _id: string
  _type: 'tournament-player'
  _createdAt: string
  _updatedAt: string
  _rev: string
  tournament?: TournamentReference
  player?: PlayerReference
  tournamentTeam?: TournamentTeamReference
  tpIndex?: number
  internal_participantType?: 'individual' | 'team'
  color?: Color
  name?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  nickname?: string
  designation?: string
  riichiImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  internal_presetTournament?: boolean
  stats?: {
    matchCount?: number
    roundCount?: number
    point?: number
    scoreMax?: number
    scoreMin?: number
    firstCount?: number
    secondCount?: number
    thirdCount?: number
    fourthCount?: number
    riichiCount?: number
    riichiCountWhenEast?: number
    riichiCountWhenNonEast?: number
    revealCount?: number
    revealCountWhenEast?: number
    revealCountWhenNonEast?: number
    waitingCount?: number
    ronCount?: number
    ronCountWhenEast?: number
    ronCountWhenNonEast?: number
    waitingWhenExhaustedCount?: number
    ronPureScoreAvg?: number
    ronPureScoreAvgWhenEast?: number
    ronPureScoreAvgWhenNonEast?: number
    ronHighYakuCount?: number
    chuckCount?: number
    chuckCountWhenEast?: number
    chuckCountWhenNonEast?: number
    chuckPureScoreAvg?: number
    chuckPureScoreAvgWhenEast?: number
    chuckPureScoreAvgWhenNonEast?: number
    chuckHighYakuCount?: number
    ronAfterRiichiCount?: number
    ronAfterRiichiPureScoreAvg?: number
    ronAfterRevealCount?: number
    ronAfterRevealPureScoreAvg?: number
    chuckAfterRiichiCount?: number
    chuckAfterRiichiPureScoreAvg?: number
    chuckAfterRevealCount?: number
    chuckAfterRevealPureScoreAvg?: number
    pointRanking?: number
    nonFourthP?: number
    nonFourthPRanking?: number
    firstAndSecondP?: number
    firstAndSecondPRanking?: number
    riichiP?: number
    riichiPRanking?: number
    ronP?: number
    ronPRanking?: number
    chuckP?: number
    chuckPRanking?: number
    revealP?: number
    revealPRanking?: number
    ronPureScoreAvgRanking?: number
    chuckPureScoreAvgRanking?: number
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Color = {
  _type: 'color'
  hex?: string
  rgba?: string
  hsl?: string
  isGradient?: boolean
  hex2?: string
  angle?: number
  css?: string
}

export type TeamReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'team'
}

export type TournamentTeam = {
  _id: string
  _type: 'tournament-team'
  _createdAt: string
  _updatedAt: string
  _rev: string
  tournament?: TournamentReference
  team?: TeamReference
  tpIndex?: number
  color?: Color
  name?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  riichiImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  stats?: {
    matchCount?: number
    roundCount?: number
    point?: number
    scoreMax?: number
    scoreMin?: number
    firstCount?: number
    secondCount?: number
    thirdCount?: number
    fourthCount?: number
    riichiCount?: number
    riichiCountWhenEast?: number
    riichiCountWhenNonEast?: number
    revealCount?: number
    revealCountWhenEast?: number
    revealCountWhenNonEast?: number
    waitingCount?: number
    ronCount?: number
    ronCountWhenEast?: number
    ronCountWhenNonEast?: number
    waitingWhenExhaustedCount?: number
    ronPureScoreAvg?: number
    ronPureScoreAvgWhenEast?: number
    ronPureScoreAvgWhenNonEast?: number
    ronHighYakuCount?: number
    chuckCount?: number
    chuckCountWhenEast?: number
    chuckCountWhenNonEast?: number
    chuckPureScoreAvg?: number
    chuckPureScoreAvgWhenEast?: number
    chuckPureScoreAvgWhenNonEast?: number
    chuckHighYakuCount?: number
    ronAfterRiichiCount?: number
    ronAfterRiichiPureScoreAvg?: number
    ronAfterRevealCount?: number
    ronAfterRevealPureScoreAvg?: number
    chuckAfterRiichiCount?: number
    chuckAfterRiichiPureScoreAvg?: number
    chuckAfterRevealCount?: number
    chuckAfterRevealPureScoreAvg?: number
    pointRanking?: number
    nonFourthP?: number
    nonFourthPRanking?: number
    firstAndSecondP?: number
    firstAndSecondPRanking?: number
    riichiP?: number
    riichiPRanking?: number
    ronP?: number
    ronPRanking?: number
    chuckP?: number
    chuckPRanking?: number
    revealP?: number
    revealPRanking?: number
    ronPureScoreAvgRanking?: number
    chuckPureScoreAvgRanking?: number
  }
}

export type Team = {
  _id: string
  _type: 'team'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  riichiImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  description?: string
  color?: Color
}

export type Player = {
  _id: string
  _type: 'player'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  description?: string
  color?: Color
  nickname?: string
  designation?: string
  riichiImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type TournamentPlayerReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'tournament-player'
}

export type Matchup = {
  _id: string
  _type: 'matchup'
  _createdAt: string
  _updatedAt: string
  _rev: string
  tournament?: TournamentReference
  name?: string
  players?: Array<
    {
      _key: string
    } & TournamentPlayerReference
  >
  startAt?: string
  result?: {
    players?: Array<{
      score?: number
      ranking?: '1' | '2' | '3' | '4'
      point?: number
      penalty?: number
      penaltyReason?: string
      _key: string
    }>
    rounds?: Array<{
      code?: string
      type?: 'unknown' | 'ron' | 'tsumo' | 'exhausted' | 'hotfix'
      players?: Array<{
        position?: 'east' | 'south' | 'west' | 'north'
        status?: 'none' | 'isRiichied' | 'isRevealed'
        isWaited?: boolean
        type?: 'none' | 'win' | 'lose'
        beforeScore?: number
        afterScore?: number
        dora?: number
        redDora?: number
        innerDora?: number
        han?: number
        fu?: number
        pureScore?: number
        yaku?: string
        _key: string
      }>
      _key: string
    }>
  }
}

export type Tournament = {
  _id: string
  _type: 'tournament'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  description?: string
  participantType?: 'individual' | 'team'
  participantColor?: Color
  participantRiichiImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type AllSanitySchemaTypes =
  | TournamentReference
  | PlayerReference
  | TournamentTeamReference
  | SanityImageAssetReference
  | TournamentPlayer
  | SanityImageCrop
  | SanityImageHotspot
  | Color
  | TeamReference
  | TournamentTeam
  | Team
  | Player
  | TournamentPlayerReference
  | Matchup
  | Tournament
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug
